#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

script:
  - npm run build.prod

deploy:
  - provider: s3
    access_key_id: AKIAIUEPSUT7HASMBYAQ
    secret_access_key:
      secure: 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
    bucket: stockyard-app
    skip_cleanup: true
    local_dir: dist/prod
    on:
      branch: master

notifications:
  email:
    on_failure: change
    on_success: change
